//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGCreations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cart()
        {
            this.orders = new HashSet<order>();
        }
    
        public int Cart_ID { get; set; }
        public int User_ID { get; set; }
        public int Product_ID { get; set; }
        public decimal Product_Price { get; set; }
        public int Product_Quantity { get; set; }
        public decimal Cart_Total { get; set; }
        public sbyte Cart_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
