//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGCreations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Order_ID { get; set; }
        public int Customer_ID { get; set; }
        public int Product_ID { get; set; }
        public int Product_Quantity { get; set; }
        public decimal Order_TotalAmount { get; set; }
        public string Order_Status { get; set; }
    
        public virtual customer_details customer_details { get; set; }
        public virtual product_details product_details { get; set; }
    }
}
