//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGCreations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_images
    {
        public int Product_Images_ID { get; set; }
        public int Product_ID { get; set; }
        public string Product_Image_Name { get; set; }
        public string Product_Image_URL { get; set; }
        public Nullable<sbyte> isPersonalisable { get; set; }
    
        public virtual product product { get; set; }
    }
}
