//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGCreations.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.carts = new HashSet<cart>();
            this.delivery_address = new HashSet<delivery_address>();
            this.orders = new HashSet<order>();
        }

        public int User_ID { get; set; }
        [Required]
        [DisplayName("Username")]
        public string User_Username { get; set; }
        [Required]
        [DisplayName("Password ")]
        public string User_Password { get; set; }
        [Required]
        [DisplayName("Firstname")]
        public string User_FirstName { get; set; }
        [Required]
        [DisplayName("Lastname")]
        public string User_LastName { get; set; }
        [Required]
        [DisplayName("Email Address")]
        public string User_Email { get; set; }
        [Required]
        [DisplayName("Contact Number")]
        public string User_ContactNo { get; set; }
        [Required]
        [DisplayName("Date of Birth")]
        public System.DateTime User_DOB { get; set; }
        [DisplayName("User Type")]
        public string User_Type { get; set; }

        public bool User_RememberMe { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_address> delivery_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
